
pull_request_rules:
  - name: Automatic approval to Renovate PRs
    conditions:
      - body~=\*\*Automerge\*\*. Enabled
    actions:
      review:
        type: APPROVE
        bot_account: Balvajs

  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
queue_rules:
  - name: default
    queue_conditions:
      - '#approved-reviews-by>=1'
      - '#approved-reviews-by>=1'
      - 'author=balvajs-renovate[bot]'
    merge_conditions: []
    merge_method: squash
