name: Dismiss stale PR reviews based on ownership
description: Dismiss all reviews that are stale. The staleness is decided based on changed files and Codeowners file.
author: Balvajs
branding:
  icon: 'git-pull-request'
  color: 'yellow'

inputs:
  ignore-files:
    required: false
    description: List of file patterns that should be ignored -> no review will be dismissed based on these files changes. The list is new line separated
  token:
    required: false
    description: GitHub token with permissions to read organization. Default is github.token
    default: ${{ github.token }}

runs:
  using: 'node16'
  main: 'dist/main.cjs'
