name: Renovate
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          private_key: ${{ secrets.RENOVATE_PEM }}
          app_id: ${{ secrets.RENOVATE_ID }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.0.5
        with:
          token: '${{ steps.get-token.outputs.token }}'
